### ISSUE TITLE
02-installation.md on the website is not update to the latest version that is on github

### ISSUE THREAD

**Issue by vasili111** [kees-z/DuplicatiDocs#50]
While ago I submited comit for `02-installation.md` and it was accepted and I see those changes on github repo. But the website docs is not updated accordingly. Can you please update website version of the `02-installation.md` to the version that is in github repo?

**Comment by kees-z** [comment]
The documentation website is synchronized automatically with the Github source. I don't have access to the website settings or sync tasks.
However, I can't find any commits in `02-installation.md` that were not applied to the documentation website. Can you give more information about which commits where not applied?

**Comment by vasili111** [comment]
At least on the part at the screenshots below. But there can be others too, because I remember I did several commits to that page in different places.

#### From github: 
![image](https://user-images.githubusercontent.com/7338799/68418330-a6307000-015d-11ea-8ecb-0aa2cef505b1.png)

#### From website: 
![image](https://user-images.githubusercontent.com/7338799/68418368-b5afb900-015d-11ea-9e88-16a2be7795a7.png)

**Comment by kees-z** [comment]
In the source, I see some non-Markdown tags at that place:

![DuplicatiDocsTags](https://user-images.githubusercontent.com/24669568/68484127-ffbb9c00-023c-11ea-8c8d-799ac0d4d7be.PNG)

I guess the websites renders these tags differently than GH does.
I removed those tags, we'll know if this helps after the next synchronization.

**Comment by kees-z** [comment]
It looks like the website renders the Markdown format a bit differently than the Github source.
Adding a few line breaks in the source seems to do the trick, GH and website look similar now:

**From github:**

![Github](https://user-images.githubusercontent.com/24669568/68983434-3419f400-080b-11ea-9185-3e0143085dc8.PNG)

**From website:**

![Website](https://user-images.githubusercontent.com/24669568/68983448-4300a680-080b-11ea-9315-262911cee1d3.PNG)

If you find another similar difference between source and website, please inform me so that I can fix it.
