### ISSUE TITLE
Clarify implications of enabling remote access

### ISSUE THREAD

**Issue by warwickmm** [kees-z/DuplicatiDocs#80]
When "Allow remote access" is enabled, access is only available by direct IP address or from the localhost by default.  This is done in to help protect against [DNS-based attacks](https://forum.duplicati.com/t/duplicati-upgrade-the-host-header-sent-by-the-client-is-not-allowed/5302/7).  Users can specify hostnames that they want to grant access to.

While this is already mentioned in the user interface, it could be helpful to clarify this in the documentation as well.

![image](https://user-images.githubusercontent.com/17345532/122785806-88e3e300-d268-11eb-90e3-fc1ed00c9655.png)

**Comment by warwickmm** [comment]
This was motivated by https://github.com/duplicati/duplicati/issues/4564.

**Comment by brainchild0** [comment]
For this problem, there is currently a message shown in the browser that reads "The host header sent by the client is not allowed". This message might be expanded to explain the details clarified above, in order to reduce dependence on  documentation to clarify the problem. I might add that this message overall is difficult to interpret in practical terms.

**Comment by kees-z** [comment]
Agreed, this information was missing in the documentation. Documentation is [updated](https://github.com/kees-z/DuplicatiDocs/commit/5422674bf4f7da5a7c37e8ec79055ebffd9fc6d8#diff-08acdc213b71e812fcd951f8dbc440f02e39bc658a191f348d5ae223f6ec92b8).

@brainchild0 This place is for commenting on the Duplicati documentation, not the product itself. For reporting bugs and feature requests, please open a ticket at https://github.com/duplicati/duplicati/issues.
